// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.awt.Desktop.Action;
import java.util.*;
public class MenuItemsBasicTests {
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\ACER\\chromedriver_win32\\chromedriver.exe");  
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void vozenRedPage() {
    driver.get("http://satbus.mk/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,1352)");
    driver.findElement(By.xpath("//*[@id=\"menu-item-3398\"]/a")).click();
    assertThat(driver.getTitle(), is("SatBUS Mk – ВОЗЕН РЕД"));
  }
  
  @Test
  public void satbusTravel() {
    driver.get("http://satbus.mk/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("#mainnav > #menu-item-3507 > a")).click();
    driver.findElement(By.linkText("ЗА НАС")).click();
    js.executeScript("window.scrollTo(0,140.8000030517578)");
    driver.findElement(By.linkText("КОНТАКТИРАЈ НЕ")).click();
    {
      WebElement element = driver.findElement(By.linkText("КОНТАКТИРАЈ НЕ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
